version : '3'
services :
        redis-server:
                restart: always
                image: 'redis'
        node-app:
                restart: 'no'
                build : .
                ports :
                  - "80:8081"
